### ISSUE TITLE
Milestone 1 - Simple Usage

### ISSUE THREAD

**Issue by lpabon** [portworx/px#18]
# Overview
This is a meta-issue describing the work that is needed to be done. Any PRs completing work here, can attach to this issue as `Part of #<issue number>`

# Work Breakdown

## Generic

- [x] Move `--show-labels` from the root persistent flag to `get volumes` and `get pvcs` commands *Kk*
- [x] Remove `-l, --selector` from root persistent flag  *Pr*
- [x] Remove `-o, --output` from the root persistent flag and move it to the ones that use it, which at the moment is `get volumes` *Kk*

## Documentation

- [ ] Development doc
- [x] Kubectl plugin doc
- [ ] How to write a px plugin doc

## Volume 
Volume work

#### SKIP
- [ ] --shared (Need to check if this means sharedv4 so that it is not confusing with `--sharedv4`) *Siva*
- [ ] --sharedv4 *Siva*
- [ ] **schedules**: _daily_, _weekly_, _monthly_: We may need to rethink the schedule (we'll come back to this *Kk*

### Get

- [x] `-l, --selector`: This is a filter which like kubectl takes labels *Pr*
- [x] Move common code to `pkg/` which is similar to `get pvc` *Kk*

### Describe

- [x] Show description of a volume in kubectl format. CLI: `px describe volume <name>` *KK*
- [x] Describe `px describe pvc <pvc name>` *KK*

### Update

- [x] Update volume: size, replica, shared, nodes *Pr*

## Cluster

- [x] cmd/status.go:31: Short: "TODO: this will move to px describe cluster" *Ravi*

## Context

- [x] Check that the endpoint is an IP or a hostname with appropriate characters *Siva*

## ClusterPair 
TBD

## Migration
TBD

# HELP

All help must have examples and good documentation.

# TODOs
The following is an output from running the following in the code:

```
git grep -n TODO | grep -v "^vendor" | sed -e "s#^#- [ ] #"
```

- [ ] cmd/contextCreate.go:77:          // TODO: If no port is provided, assume 9020
- [ ] cmd/contextCreate.go:85:          // TODO: Should check if the file exists
- [ ] cmd/contextCreate.go:96:          // TODO: Should check if the file exists
- [ ] cmd/createCloudmigration.go:42:   Long:  `TODO Add long description`,
- [ ] cmd/createClusterpair.go:48:      Example: "$ px create clusterpair TODO ADD EXAMPLEs",
- [ ] cmd/createClusterpair.go:49:      Long: `TODO
- [ ] cmd/createVolume.go:46:   // TODO:
- [ ] cmd/createVolume.go:67:   // TODO bring the flags from rootCmd
- [ ] cmd/createVolume.go:69:   // TODO add more flags here
- [ ] cmd/getPvc.go:183:        // TODO: Make this a pkg/volume call
- [ ] cmd/getVolumes.go:48:     // TODO: Place here support for selectors and move the flags from the rootCmd
- [ ] cmd/root.go:84:   // TODO: move these flags out of persistent
- [ ] cmd/status.go:30: // TODO

- [ ] pkg/contextconfig/contextconfig.go:138:// TODO have GetNamedContext and GetCurrent() call a common helper function
- [ ] pkg/grpc/client.go:62:                    // TODO: Remove logrus usage
- [ ] pkg/plugin/plugin.go:29:// TODO: Add comments
- [ ] pkg/portworx/connect.go:27:// TODO: Add Support to connect to a context name
- [ ] pkg/portworx/pxVolumeOps.go:262:// TODO:Break this up into smaller functions

# Other commands
* `px log <object> <type>`

# Backlog for Milestone 2
- [ ] stats.
- [ ] alerts. This is tricky because alerts are not part of the SDK. Something else needs to be done in openstorage for this to be used in Px. Or we can use the internal-SDK.
- [ ] auth (Generate Tokens), role (Role management), volume access
- [ ] storage-policy
- [ ] schedule-policy
- [ ] secrets (This may not be part of the SDK and so we may have to depend on something else)
- [ ] objectstore
- [ ] cloudsnap
- [ ] cmd/contextCreate.go:89:          // TODO: Check the token is a JWT token
- [ ] `px install --csi --kube-config=... --stork` - New command to install px
