### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by lpabon** [portworx/px#48]
# Infrastructure
- [ ] Development docs to show how to write Examples and docs - _LP_
     - [ ] All code has been adjusted.
- [ ] Support for external packages - _LP_

# Generic
- [ ] stats.
- [ ] alerts. This is tricky because alerts are not part of the SDK. Something else needs to be done in openstorage for this to be used in Px. Or we can use the internal-SDK. This may have to be pushed to M3.

# Auth
- [ ] [TLS support](https://github.com/libopenstorage/libopenstorage.github.io/blob/master/examples/golang/main.go#L65-L75)
- [ ] [Token support](https://github.com/libopenstorage/libopenstorage.github.io/blob/master/examples/golang/main.go#L33-L62). See [Tutorial](https://libopenstorage.github.io/w/tutorial.html#setting-up-security-in-the-mock-sdk-server)
- [ ] role (Role management) - [See pxctl](https://docs.portworx.com/reference/cli/role/) Except everything in yaml. as input
- [ ] volume access control - [See pxctl](https://docs.portworx.com/reference/cli/volume-access/)

**Comment by raviprasadsn** [comment]
Will take up Role management

**Comment by siva-portworx** [comment]
Will take up Volume access control.

**Comment by kkg-portworx** [comment]
Will pick up stats

**Comment by prashanthpx** [comment]
Will pick up Token support.

**Comment by siva-portworx** [comment]
Along with InternalSDK tasks, I will pick up Volume access control.
